alter table notification_user
add column username varchar(100) unique,
add column publish_id bigint generated by default as identity,
add column pwd_hash text;

create index notification_username_idx on notification_user(username);
